import React, { useState } from 'react';
import { DebateState, HighlightSlide } from '../App';
import { 
  Sparkles, Video, Mic, Plus, Play, Pause, Trash2, ArrowUp, ArrowDown, 
  Tv, RefreshCw, Flame, MessageSquare, Tag, Upload, Check, AlertCircle,
  FileVideo, FileAudio, Layers, ShieldAlert, Repeat, ChevronRight
} from 'lucide-react';

interface HighlightManagerProps {
  state: DebateState;
  onStateUpdate: (partialState: Partial<DebateState>) => void;
  setActiveTab: (tab: string) => void;
}

export default function HighlightManager({ state, onStateUpdate, setActiveTab }: HighlightManagerProps) {
  const slides: HighlightSlide[] = state.highlightSlides || [];
  const currentIndex = state.currentHighlightSlideIndex || 0;
  const isPlaying = state.highlightSlideshowPlaying ?? false;

  // New Slide Modal State
  const [showAddModal, setShowAddModal] = useState(false);
  const [slideType, setSlideType] = useState<'video' | 'audio' | 'claim' | 'custom'>('video');
  const [title, setTitle] = useState('');
  const [subtitle, setSubtitle] = useState('');
  const [content, setContent] = useState('');
  const [speakerName, setSpeakerName] = useState('');
  const [speakerRole, setSpeakerRole] = useState<'PROPOSER' | 'CONTRARY' | 'NEUTRAL'>('PROPOSER');
  const [counterClaimCount, setCounterClaimCount] = useState<number>(0);
  const [seatSwapsCount, setSeatSwapsCount] = useState<number>(0);
  const [tagsInput, setTagsInput] = useState('');
  
  // Media upload states
  const [mediaUrl, setMediaUrl] = useState('');
  const [isUploading, setIsUploading] = useState(false);
  const [uploadError, setUploadError] = useState('');
  const [uploadSuccess, setUploadSuccess] = useState('');

  // Auto-generation algorithm
  const handleAutoGenerate = () => {
    const generated: HighlightSlide[] = [];
    const claims = state.claims || [];
    const counterClaims = state.counterClaims || [];
    const chatQuestions = state.chatQuestions || [];

    // Map claim counterclaims
    const counterCounts: Record<string, number> = {};
    counterClaims.forEach(c => {
      counterCounts[c.claimId] = (counterCounts[c.claimId] || 0) + 1;
    });

    // 1. Hot contested claims (claims with most counterclaims)
    const sortedClaims = [...claims].sort((a, b) => (counterCounts[b.id] || 0) - (counterCounts[a.id] || 0));
    sortedClaims.slice(0, 4).forEach((claim, idx) => {
      const cCount = counterCounts[claim.id] || 0;
      const speakerObj = state.participants?.find(p => p.name.toLowerCase() === claim.speakerName.toLowerCase());
      
      generated.push({
        id: `auto-claim-${claim.id}-${Date.now()}`,
        type: cCount > 0 ? 'counterclaim' : 'claim',
        title: cCount > 0 ? `🔥 Hot Contested Claim #${idx + 1}` : `Key Point • ${claim.round || 'Round 1'}`,
        subtitle: `Spoken during ${claim.phase || 'Debate Phase'}`,
        content: claim.text,
        speakerName: claim.speakerName,
        speakerRole: speakerObj?.role || 'PROPOSER',
        counterClaimCount: cCount,
        seatSwapsCount: Math.min(3, cCount + 1),
        tags: cCount > 0 ? ['#HotDebate', '#Countered', '#KeyPoint'] : ['#KeyArgument', '#Highlight'],
        createdAt: Date.now(),
        isAutoGenerated: true
      });
    });

    // 2. High upvoted Chat Questions
    const topQuestions = [...chatQuestions].sort((a, b) => b.votes - a.votes).slice(0, 2);
    topQuestions.forEach((q, idx) => {
      generated.push({
        id: `auto-q-${q.id}-${Date.now()}`,
        type: 'hot_topic',
        title: `💬 Audience Challenge #${idx + 1}`,
        subtitle: `Community Question with ${q.votes} Upvotes`,
        content: `"${q.text}"`,
        speakerName: q.author,
        speakerRole: 'NEUTRAL',
        votesCount: q.votes,
        tags: ['#AudienceFavorite', '#CommunityChallenge'],
        createdAt: Date.now(),
        isAutoGenerated: true
      });
    });

    // 3. (Intro slide removed per user requirement)

    onStateUpdate({
      highlightSlides: generated,
      currentHighlightSlideIndex: 0,
      highlightSlideshowPlaying: true
    });
  };

  // Upload Video or Audio File to /api/upload-video
  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsUploading(true);
    setUploadError('');
    setUploadSuccess('');

    try {
      const reader = new FileReader();
      reader.onload = async () => {
        const base64String = (reader.result as string).split(',')[1];
        const res = await fetch('/api/upload-video', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            filename: file.name,
            base64Data: base64String
          })
        });

        const data = await res.json();
        setIsUploading(false);

        if (data.success && data.url) {
          setMediaUrl(data.url);
          setUploadSuccess(`File uploaded successfully: ${file.name}`);
        } else {
          setUploadError(data.error || 'Failed to upload media file.');
        }
      };

      reader.onerror = () => {
        setIsUploading(false);
        setUploadError('Failed to read local media file.');
      };

      reader.readAsDataURL(file);
    } catch (err: any) {
      setIsUploading(false);
      setUploadError(err.message || 'File upload failed.');
    }
  };

  const handleCreateSlideSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim() && !content.trim()) return;

    const parsedTags = tagsInput
      ? tagsInput.split(',').map(t => t.trim().startsWith('#') ? t.trim() : `#${t.trim()}`)
      : slideType === 'video' ? ['#VideoClip'] : slideType === 'audio' ? ['#AudioClip'] : ['#CustomHighlight'];

    const newSlide: HighlightSlide = {
      id: 'slide-' + Date.now(),
      type: slideType === 'video' ? 'video' : slideType === 'audio' ? 'audio' : slideType === 'claim' ? 'claim' : 'custom',
      title: title.trim() || (slideType === 'video' ? 'Video Highlight Clip' : 'Audio Quote Clip'),
      subtitle: subtitle.trim() || undefined,
      content: content.trim() || (mediaUrl ? 'Media Clip Played Live on Stage' : 'Custom Highlight Statement'),
      speakerName: speakerName.trim() || undefined,
      speakerRole,
      mediaUrl: mediaUrl || undefined,
      mediaType: slideType === 'video' ? 'video' : slideType === 'audio' ? 'audio' : undefined,
      counterClaimCount: Number(counterClaimCount) || 0,
      seatSwapsCount: Number(seatSwapsCount) || 0,
      tags: parsedTags,
      createdAt: Date.now(),
      isAutoGenerated: false
    };

    const updatedSlides = [...slides, newSlide];
    onStateUpdate({
      highlightSlides: updatedSlides,
      currentHighlightSlideIndex: updatedSlides.length - 1
    });

    // Reset Form
    setTitle('');
    setSubtitle('');
    setContent('');
    setSpeakerName('');
    setMediaUrl('');
    setCounterClaimCount(0);
    setSeatSwapsCount(0);
    setTagsInput('');
    setUploadSuccess('');
    setUploadError('');
    setShowAddModal(false);
  };

  const handleDeleteSlide = (id: string) => {
    const updated = slides.filter(s => s.id !== id);
    onStateUpdate({
      highlightSlides: updated,
      currentHighlightSlideIndex: Math.max(0, Math.min(currentIndex, updated.length - 1))
    });
  };

  const handleMoveSlide = (index: number, direction: 'up' | 'down') => {
    const targetIndex = direction === 'up' ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= slides.length) return;

    const newSlides = [...slides];
    const temp = newSlides[index];
    newSlides[index] = newSlides[targetIndex];
    newSlides[targetIndex] = temp;

    onStateUpdate({
      highlightSlides: newSlides,
      currentHighlightSlideIndex: targetIndex
    });
  };

  const handleProjectOnStage = (index: number) => {
    onStateUpdate({
      currentPhase: 'HIGHLIGHT',
      currentHighlightSlideIndex: index,
      highlightSlideshowPlaying: true
    });
  };

  return (
    <div className="flex-1 flex flex-col p-6 overflow-hidden">
      {/* HEADER BAR */}
      <div className="flex flex-wrap items-center justify-between gap-4 mb-5 shrink-0">
        <div>
          <h1 className="text-xl font-black text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-[#f97316]" /> Debate Highlights Deck
          </h1>
          <p className="text-xs text-[#64748b]">
            Auto-detect hot claims, upload video/audio clips, and present a cinematic slideshow live on stage.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {/* AUTO GENERATE BUTTON */}
          <button
            onClick={handleAutoGenerate}
            className="bg-[#181c2a] hover:bg-[#252b3f] text-[#f97316] border border-[#f97316]/30 text-xs font-bold px-3.5 py-2 rounded-xl transition-all cursor-pointer flex items-center gap-1.5 shadow-sm"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            Auto-Detect Hot Spots
          </button>

          {/* ADD CLIP / SLIDE BUTTON */}
          <button
            onClick={() => setShowAddModal(true)}
            className="bg-[#f97316] hover:bg-[#ea580c] text-white text-xs font-bold px-4 py-2 rounded-xl transition-all cursor-pointer flex items-center gap-1.5 shadow-md shadow-[#f97316]/20"
          >
            <Plus className="w-4 h-4" /> Add Video / Slide
          </button>

          {/* PRESENT ON STAGE BUTTON */}
          <button
            onClick={() => {
              onStateUpdate({ currentPhase: 'HIGHLIGHT', highlightSlideshowPlaying: true });
            }}
            className={`text-xs font-black uppercase tracking-wider px-4 py-2 rounded-xl transition-all cursor-pointer flex items-center gap-2 border shadow-lg ${
              state.currentPhase === 'HIGHLIGHT'
                ? 'bg-emerald-500 text-white border-emerald-400 shadow-emerald-500/20'
                : 'bg-gradient-to-r from-purple-600 to-indigo-600 text-white border-purple-400/30'
            }`}
          >
            <Tv className="w-4 h-4" />
            {state.currentPhase === 'HIGHLIGHT' ? 'Live on Stage Now' : 'Present Reel on Stage'}
          </button>
        </div>
      </div>

      {/* MAIN CONTENT AREA */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 gap-6 overflow-hidden">
        {/* LEFT 2 COLUMNS: SLIDE DECK LIST */}
        <div className="lg:col-span-2 bg-[#101114] border border-[#1d1e24] rounded-2xl p-4 flex flex-col overflow-hidden">
          <div className="flex items-center justify-between pb-3 border-b border-[#1d1e24] mb-3 shrink-0">
            <span className="text-xs font-black text-gray-400 uppercase tracking-wider flex items-center gap-2">
              <Layers className="w-4 h-4 text-[#f97316]" /> Slide Deck Queue ({slides.length} Slides)
            </span>

            {/* PLAY / PAUSE SLIDESHOW CONTROL */}
            {slides.length > 0 && (
              <button
                onClick={() => onStateUpdate({ highlightSlideshowPlaying: !isPlaying })}
                className="bg-[#181a24] hover:bg-[#202433] text-gray-300 text-xs font-bold px-3 py-1.5 rounded-lg border border-[#2d2f39] transition-all cursor-pointer flex items-center gap-1.5"
              >
                {isPlaying ? <Pause className="w-3.5 h-3.5 text-amber-400" /> : <Play className="w-3.5 h-3.5 text-emerald-400" />}
                {isPlaying ? 'Pause Slideshow' : 'Auto-Play Slideshow'}
              </button>
            )}
          </div>

          {/* SLIDES LIST */}
          <div className="flex-1 overflow-y-auto pr-1 flex flex-col gap-3">
            {slides.length === 0 ? (
              <div className="text-center py-16 flex flex-col items-center justify-center text-gray-500 gap-3">
                <Sparkles className="w-10 h-10 text-gray-600 animate-pulse" />
                <p className="text-xs font-semibold max-w-xs">
                  No highlight slides added yet. Click "Auto-Detect Hot Spots" to scan active debate claims, or insert custom video clips.
                </p>
                <button
                  onClick={handleAutoGenerate}
                  className="bg-[#f97316] text-white text-xs font-bold px-4 py-2 rounded-xl shadow-md cursor-pointer hover:bg-[#ea580c] transition-all mt-2"
                >
                  ⚡ Auto-Detect Hot Spots
                </button>
              </div>
            ) : (
              slides.map((slide, idx) => {
                const isActiveOnStage = currentIndex === idx && state.currentPhase === 'HIGHLIGHT';
                return (
                  <div
                    key={slide.id || idx}
                    className={`bg-[#0a0b0e] border rounded-xl p-4 transition-all flex flex-col gap-2.5 relative group ${
                      isActiveOnStage
                        ? 'border-emerald-500/60 bg-emerald-500/5 shadow-md shadow-emerald-500/10'
                        : currentIndex === idx
                        ? 'border-[#f97316]/60 bg-[#f97316]/5'
                        : 'border-[#1d1e24] hover:border-[#2d2f39]'
                    }`}
                  >
                    {/* SLIDE HEADER */}
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span className="text-[10px] font-mono font-bold text-gray-500">
                          #{idx + 1}
                        </span>

                        {/* SLIDE TYPE BADGE */}
                        {slide.type === 'video' ? (
                          <span className="bg-blue-500/10 border border-blue-500/30 text-blue-400 text-[9px] font-black uppercase px-2 py-0.5 rounded flex items-center gap-1">
                            <Video className="w-3 h-3" /> Video Clip
                          </span>
                        ) : slide.type === 'audio' ? (
                          <span className="bg-purple-500/10 border border-purple-500/30 text-purple-400 text-[9px] font-black uppercase px-2 py-0.5 rounded flex items-center gap-1">
                            <Mic className="w-3 h-3" /> Audio Clip
                          </span>
                        ) : slide.type === 'counterclaim' || (slide.counterClaimCount || 0) > 0 ? (
                          <span className="bg-red-500/10 border border-red-500/30 text-red-400 text-[9px] font-black uppercase px-2 py-0.5 rounded flex items-center gap-1">
                            <Flame className="w-3 h-3 fill-red-400" /> Hot Counterclaim
                          </span>
                        ) : (
                          <span className="bg-[#f97316]/10 border border-[#f97316]/30 text-[#f97316] text-[9px] font-black uppercase px-2 py-0.5 rounded flex items-center gap-1">
                            <Sparkles className="w-3 h-3" /> Debate Claim
                          </span>
                        )}

                        {slide.isAutoGenerated && (
                          <span className="text-[9px] text-gray-500 font-bold bg-[#16171d] px-1.5 py-0.5 rounded border border-[#2d2f39]">
                            Auto-Generated
                          </span>
                        )}
                      </div>

                      {/* SLIDE ACTIONS */}
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => handleProjectOnStage(idx)}
                          className="bg-emerald-600 hover:bg-emerald-500 text-white text-[10px] font-bold px-2.5 py-1 rounded-lg transition-all cursor-pointer flex items-center gap-1 shadow"
                          title="Project this slide live on stage"
                        >
                          <Tv className="w-3 h-3" /> Project
                        </button>
                        <button
                          onClick={() => handleMoveSlide(idx, 'up')}
                          disabled={idx === 0}
                          className="p-1 text-gray-400 hover:text-white disabled:opacity-30 cursor-pointer"
                          title="Move Up"
                        >
                          <ArrowUp className="w-3.5 h-3.5" />
                        </button>
                        <button
                          onClick={() => handleMoveSlide(idx, 'down')}
                          disabled={idx === slides.length - 1}
                          className="p-1 text-gray-400 hover:text-white disabled:opacity-30 cursor-pointer"
                          title="Move Down"
                        >
                          <ArrowDown className="w-3.5 h-3.5" />
                        </button>
                        <button
                          onClick={() => handleDeleteSlide(slide.id)}
                          className="p-1 text-gray-500 hover:text-red-400 cursor-pointer"
                          title="Delete Slide"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>

                    {/* SLIDE TITLE & CONTENT */}
                    <div className="flex flex-col gap-1">
                      <h3 className="text-sm font-black text-white">
                        {slide.title}
                      </h3>
                      {slide.content && (
                        <p className="text-xs text-gray-300 font-medium line-clamp-2 leading-relaxed">
                          "{slide.content}"
                        </p>
                      )}
                    </div>

                    {/* MEDIA PREVIEW IF ANY */}
                    {slide.mediaUrl && (
                      <div className="bg-[#12141c] border border-[#272a38] p-2 rounded-lg flex items-center justify-between text-xs text-gray-300">
                        <span className="truncate max-w-xs font-mono text-[10px] text-gray-400">
                          {slide.mediaUrl}
                        </span>
                        <span className="text-[9px] font-bold text-emerald-400 uppercase bg-emerald-500/10 px-2 py-0.5 rounded">
                          Media Ready
                        </span>
                      </div>
                    )}

                    {/* FOOTER BADGES */}
                    <div className="flex items-center justify-between pt-1 text-[10px] text-gray-400 font-semibold border-t border-[#181a22]">
                      <div className="flex items-center gap-2">
                        {slide.speakerName && (
                          <span>🗣️ {slide.speakerName}</span>
                        )}
                        {(slide.counterClaimCount || 0) > 0 && (
                          <span className="text-red-400 font-bold">
                            🔥 {slide.counterClaimCount} Counterclaims
                          </span>
                        )}
                      </div>

                      {slide.tags && (
                        <div className="flex gap-1">
                          {slide.tags.map((t, tIdx) => (
                            <span key={tIdx} className="text-gray-500 font-mono text-[9px]">
                              {t}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* RIGHT COLUMN: STAGE PREVIEW BOX & QUICK STATS */}
        <div className="flex flex-col gap-4 overflow-hidden">
          {/* PREVIEW BOX */}
          <div className="bg-[#101114] border border-[#1d1e24] rounded-2xl p-4 flex flex-col">
            <span className="text-xs font-black text-gray-400 uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <Tv className="w-4 h-4 text-emerald-400" /> Active Stage Preview
            </span>

            {slides.length > 0 && slides[currentIndex] ? (
              <div className="bg-[#040508] border border-[#2d3142] rounded-xl p-4 flex flex-col justify-between aspect-video relative overflow-hidden text-white">
                <span className="bg-[#f97316] text-white text-[8px] font-black uppercase px-2 py-0.5 rounded w-max">
                  SLIDE {currentIndex + 1} / {slides.length}
                </span>

                <div className="my-auto">
                  <h4 className="text-xs font-black text-white uppercase tracking-tight line-clamp-1 mb-1">
                    {slides[currentIndex].title}
                  </h4>
                  <p className="text-[10px] text-gray-300 font-serif italic line-clamp-2">
                    "{slides[currentIndex].content}"
                  </p>
                </div>

                <div className="flex items-center justify-between text-[9px] text-gray-400 border-t border-gray-800 pt-1">
                  <span>{slides[currentIndex].speakerName || 'Speaker'}</span>
                  <span>{state.currentPhase === 'HIGHLIGHT' ? '🔴 LIVE ON STAGE' : 'STAGE READY'}</span>
                </div>
              </div>
            ) : (
              <div className="bg-[#040508] border border-dashed border-gray-800 rounded-xl aspect-video flex items-center justify-center text-center p-4 text-gray-500 text-xs font-semibold">
                No active slide selected
              </div>
            )}
          </div>

          {/* QUICK SUMMARY CARD */}
          <div className="bg-[#101114] border border-[#1d1e24] rounded-2xl p-4 flex flex-col gap-3">
            <span className="text-xs font-black text-white uppercase tracking-wider">
              Reel Intelligence
            </span>
            <div className="grid grid-cols-2 gap-2 text-center">
              <div className="bg-[#16171d] p-3 rounded-xl border border-[#2d2f39]">
                <span className="text-lg font-black text-[#f97316]">{state.claims?.length || 0}</span>
                <p className="text-[9px] font-bold text-gray-400 uppercase">Recorded Claims</p>
              </div>
              <div className="bg-[#16171d] p-3 rounded-xl border border-[#2d2f39]">
                <span className="text-lg font-black text-red-400">{state.counterClaims?.length || 0}</span>
                <p className="text-[9px] font-bold text-gray-400 uppercase">Counterclaims</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* CREATE SLIDE MODAL */}
      {showAddModal && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-4">
          <div className="bg-[#101114] border border-[#2d2f39] rounded-2xl p-6 max-w-xl w-full flex flex-col gap-4 shadow-2xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-[#2d2f39] pb-3">
              <h3 className="text-sm font-black text-white uppercase tracking-wider flex items-center gap-2">
                <Plus className="w-4 h-4 text-[#f97316]" /> Add Highlight Slide or Media Clip
              </h3>
              <button
                onClick={() => setShowAddModal(false)}
                className="text-gray-400 hover:text-white font-bold text-sm cursor-pointer"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleCreateSlideSubmit} className="flex flex-col gap-4">
              {/* TYPE SELECTOR */}
              <div className="grid grid-cols-4 gap-2 text-center text-xs font-bold">
                {[
                  { id: 'video', label: '📹 Video Clip', icon: Video },
                  { id: 'audio', label: '🎙️ Audio Clip', icon: Mic },
                  { id: 'claim', label: '💬 Claim Statement', icon: MessageSquare },
                  { id: 'custom', label: '🎨 Custom Slide', icon: Layers }
                ].map(tab => (
                  <button
                    key={tab.id}
                    type="button"
                    onClick={() => setSlideType(tab.id as any)}
                    className={`p-2.5 rounded-xl border transition-all cursor-pointer ${
                      slideType === tab.id
                        ? 'bg-[#f97316] text-white border-[#f97316]'
                        : 'bg-[#16171d] text-gray-400 border-[#2d2f39] hover:text-white'
                    }`}
                  >
                    {tab.label}
                  </button>
                ))}
              </div>

              {/* MEDIA FILE UPLOAD FIELD IF VIDEO OR AUDIO */}
              {(slideType === 'video' || slideType === 'audio') && (
                <div className="bg-[#16171d] border border-[#2d2f39] p-4 rounded-xl flex flex-col gap-2">
                  <label className="text-[10px] font-black text-gray-400 uppercase">
                    Upload Local {slideType === 'video' ? 'Video (MP4/WebM)' : 'Audio (MP3/WAV)'} File
                  </label>
                  <input
                    type="file"
                    accept={slideType === 'video' ? 'video/*' : 'audio/*'}
                    onChange={handleFileUpload}
                    className="text-xs text-gray-300 file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:text-xs file:font-bold file:bg-[#f97316] file:text-white hover:file:bg-[#ea580c] cursor-pointer"
                  />

                  {isUploading && (
                    <span className="text-xs text-[#f97316] font-bold animate-pulse">
                      Uploading media clip to server...
                    </span>
                  )}
                  {uploadSuccess && (
                    <span className="text-xs text-emerald-400 font-bold flex items-center gap-1">
                      <Check className="w-3.5 h-3.5" /> {uploadSuccess}
                    </span>
                  )}
                  {uploadError && (
                    <span className="text-xs text-red-400 font-bold flex items-center gap-1">
                      <AlertCircle className="w-3.5 h-3.5" /> {uploadError}
                    </span>
                  )}

                  <div className="flex flex-col gap-1 mt-1">
                    <label className="text-[10px] font-black text-gray-500 uppercase">Or Media Direct URL</label>
                    <input
                      type="text"
                      placeholder="https://example.com/clip.mp4"
                      value={mediaUrl}
                      onChange={(e) => setMediaUrl(e.target.value)}
                      className="bg-[#101114] border border-[#2d2f39] text-xs text-white p-2.5 rounded-xl"
                    />
                  </div>
                </div>
              )}

              {/* TITLE & SUBTITLE */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] font-black text-gray-400 uppercase">Slide Title</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Critical Rebuttal Moment"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    className="bg-[#16171d] border border-[#2d2f39] text-xs text-white p-2.5 rounded-xl"
                  />
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] font-black text-gray-400 uppercase">Subtitle / Context</label>
                  <input
                    type="text"
                    placeholder="e.g. Spoken in Rebuttal Round 2"
                    value={subtitle}
                    onChange={(e) => setSubtitle(e.target.value)}
                    className="bg-[#16171d] border border-[#2d2f39] text-xs text-white p-2.5 rounded-xl"
                  />
                </div>
              </div>

              {/* CONTENT / QUOTE */}
              <div className="flex flex-col gap-1.5">
                <label className="text-[10px] font-black text-gray-400 uppercase">Quote / Main Statement Text</label>
                <textarea
                  rows={3}
                  placeholder="Enter quote, argument text, or video transcript description..."
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  className="bg-[#16171d] border border-[#2d2f39] text-xs text-white p-2.5 rounded-xl"
                />
              </div>

              {/* SPEAKER & ROLE */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] font-black text-gray-400 uppercase">Speaker Name</label>
                  <input
                    type="text"
                    placeholder="e.g. @speaker_john"
                    value={speakerName}
                    onChange={(e) => setSpeakerName(e.target.value)}
                    className="bg-[#16171d] border border-[#2d2f39] text-xs text-white p-2.5 rounded-xl"
                  />
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] font-black text-gray-400 uppercase">Speaker Side</label>
                  <select
                    value={speakerRole}
                    onChange={(e) => setSpeakerRole(e.target.value as any)}
                    className="bg-[#16171d] border border-[#2d2f39] text-xs text-white p-2.5 rounded-xl cursor-pointer"
                  >
                    <option value="PROPOSER">{state.settings?.proTeamName || 'Affirmative'}</option>
                    <option value="CONTRARY">{state.settings?.conTeamName || 'Opposition'}</option>
                    <option value="NEUTRAL">Neutral / Audience</option>
                  </select>
                </div>
              </div>

              {/* METRICS & TAGS */}
              <div className="grid grid-cols-3 gap-3">
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] font-black text-gray-400 uppercase">Counterclaims</label>
                  <input
                    type="number"
                    min="0"
                    value={counterClaimCount}
                    onChange={(e) => setCounterClaimCount(Number(e.target.value))}
                    className="bg-[#16171d] border border-[#2d2f39] text-xs text-white p-2.5 rounded-xl"
                  />
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] font-black text-gray-400 uppercase">Seat Swaps</label>
                  <input
                    type="number"
                    min="0"
                    value={seatSwapsCount}
                    onChange={(e) => setSeatSwapsCount(Number(e.target.value))}
                    className="bg-[#16171d] border border-[#2d2f39] text-xs text-white p-2.5 rounded-xl"
                  />
                </div>
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] font-black text-gray-400 uppercase">Tags (comma sep)</label>
                  <input
                    type="text"
                    placeholder="#HotDebate, #Countered"
                    value={tagsInput}
                    onChange={(e) => setTagsInput(e.target.value)}
                    className="bg-[#16171d] border border-[#2d2f39] text-xs text-white p-2.5 rounded-xl"
                  />
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2 border-t border-[#2d2f39]">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="bg-[#16171d] text-gray-400 text-xs font-bold px-4 py-2 rounded-xl border border-[#2d2f39] cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="bg-[#f97316] hover:bg-[#ea580c] text-white text-xs font-bold px-5 py-2 rounded-xl cursor-pointer shadow-md"
                >
                  Save Slide to Reel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
